// Customizable Metrics Configuration

export type MetricAggregation = 'avg' | 'max' | 'min' | 'median' | 'sum' | 'rate' | 'percentile';
export type MetricCategory = 'overall' | 'auto' | 'teleop' | 'endgame' | 'fuel' | 'quality' | 'reliability';

export interface MetricColumn {
  id: string;
  label: string;
  field: string; // Field from TeamStatistics (or TeamStatistics in mock mode)
  rawMetric?: string; // If set, compute on-the-fly from raw scout entries instead of reading `field`
  fuelField?: string; // If set, read from TeamFuelStats instead of TeamStatistics
  aggregation: MetricAggregation;
  format: 'number' | 'percentage' | 'time' | 'count' | 'climbLevel';
  decimals: number;
  enabled: boolean;
  percentileValue?: number; // 25, 75, 90, etc. Only used when aggregation === 'percentile'
  description?: string;
  category: MetricCategory;
}

export interface MetricsConfig {
  columns: MetricColumn[];
  lastUpdated: string;
}

// All available metrics from TeamStatistics, organized by category
// NOTE: The order here determines the default column order in the TeamList table.
// Enabled metrics are grouped: Overall → Auto → Fuel/Teleop → Endgame
export const DEFAULT_METRICS: MetricColumn[] = [
  // ========== OVERALL ==========
  {
    id: 'avgTotalPoints',
    label: 'Avg Points',
    field: 'avgTotalPoints',
    fuelField: 'avgTotalPointsScored',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: true,
    description: 'Average attributed total points per match (FMS data)',
    category: 'overall',
  },
  {
    id: 'maxTotalPoints',
    label: 'Max Points',
    field: 'maxTotalPoints',
    aggregation: 'max',
    format: 'number',
    decimals: 0,
    enabled: false,
    description: 'Maximum estimated total points in a single match',
    category: 'overall',
  },
  {
    id: 'avgAutoPoints',
    label: 'Avg Auto Pts',
    field: 'avgAutoPoints',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average autonomous points (fuel + auto climb)',
    category: 'overall',
  },
  {
    id: 'avgTeleopPoints',
    label: 'Avg Teleop Pts',
    field: 'avgTeleopPoints',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average teleop points',
    category: 'overall',
  },
  {
    id: 'avgEndgamePoints',
    label: 'Avg Endgame Pts',
    field: 'avgEndgamePoints',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average endgame climb points',
    category: 'overall',
  },
  {
    id: 'totalTotalPoints',
    label: 'Total Points (Sum)',
    field: 'totalTotalPoints',
    aggregation: 'sum',
    format: 'number',
    decimals: 0,
    enabled: false,
    description: 'Sum of estimated points across all matches',
    category: 'overall',
  },

  // ========== AUTONOMOUS ==========
  {
    id: 'autoClimbCount',
    label: 'Auto Climb Count',
    field: 'autoClimbCount',
    aggregation: 'sum',
    format: 'count',
    decimals: 0,
    enabled: true,
    description: 'Number of matches with successful auto climb (shown as X/N)',
    category: 'auto',
  },
  {
    id: 'fuelAvgAutoScored',
    label: 'Avg Auto Scored',
    field: 'avgAutoScored',
    fuelField: 'avgAutoScored',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: true,
    description: 'Avg auto balls scored per match (FMS auto count, power curve attributed)',
    category: 'auto',
  },
  {
    id: 'autoClimbRate',
    label: 'Auto Climb %',
    field: 'autoClimbRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches with successful auto climb',
    category: 'auto',
  },
  {
    id: 'autoDidNothingRate',
    label: 'Auto Did Nothing %',
    field: 'autoDidNothingRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches where robot did nothing in auto',
    category: 'auto',
  },
  {
    id: 'autoDidNothingCount',
    label: 'Auto Did Nothing Count',
    field: 'autoDidNothingCount',
    aggregation: 'sum',
    format: 'count',
    decimals: 0,
    enabled: false,
    description: 'Number of matches where robot did nothing in auto (shown as X/N)',
    category: 'auto',
  },

  // ========== FUEL SCORING (Teleop-focused & Total) ==========
  {
    id: 'fuelAvgMoved',
    label: 'Avg Moved',
    field: 'avgMoved',
    fuelField: 'avgMoved',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: true,
    description: 'Avg total balls moved per match (shots + passes, from action data)',
    category: 'fuel',
  },
  {
    id: 'fuelAvgPasses',
    label: 'Avg Passes',
    field: 'avgPasses',
    fuelField: 'avgPasses',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: true,
    description: 'Avg balls passed per match (from action data, excludes shots)',
    category: 'fuel',
  },
  {
    id: 'fuelAvgShots',
    label: 'Avg Shots',
    field: 'avgShots',
    fuelField: 'avgShots',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Avg scoring attempts per match (from action data)',
    category: 'fuel',
  },
  {
    id: 'fuelAvgScored',
    label: 'Avg Scored',
    field: 'avgShotsScored',
    fuelField: 'avgShotsScored',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: true,
    description: 'Avg balls scored per match (attributed from FMS via power curve β=0.7)',
    category: 'fuel',
  },
  {
    id: 'fuelAvgTeleopScored',
    label: 'Avg Teleop Scored',
    field: 'avgTeleopScored',
    fuelField: 'avgTeleopScored',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: true,
    description: 'Avg teleop balls scored per match (FMS teleop count, power curve attributed)',
    category: 'fuel',
  },
  {
    id: 'fuelScoringAccuracy',
    label: 'Scoring Accuracy',
    field: 'scoringAccuracy',
    fuelField: 'scoringAccuracy',
    aggregation: 'avg',
    format: 'percentage',
    decimals: 0,
    enabled: true,
    description: 'Weighted scoring accuracy: total scored / total shots (FMS-grounded)',
    category: 'fuel',
  },
  // Disabled fuel metrics
  {
    id: 'avgTotalFuelEstimate',
    label: 'Avg Fuel Moved',
    field: 'avgTotalFuelEstimate',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average estimated total fuel moved per match (summary-based, includes orphaned presses)',
    category: 'fuel',
  },
  {
    id: 'avgAutoFuelEstimate',
    label: 'Avg Auto Fuel',
    field: 'avgAutoFuelEstimate',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average estimated auto fuel (FUEL_SCORE + bonus buckets)',
    category: 'fuel',
  },
  {
    id: 'avgTeleopFuelEstimate',
    label: 'Avg Teleop Fuel',
    field: 'avgTeleopFuelEstimate',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average estimated teleop fuel (FUEL_SCORE + bonus buckets)',
    category: 'fuel',
  },
  {
    id: 'maxTotalFuelEstimate',
    label: 'Max Total Fuel',
    field: 'maxTotalFuelEstimate',
    aggregation: 'max',
    format: 'number',
    decimals: 0,
    enabled: false,
    description: 'Maximum estimated total fuel in a single match',
    category: 'fuel',
  },
  {
    id: 'avgAutoFuelScore',
    label: 'Avg Auto Raw',
    field: 'avgAutoFuelScore',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average raw FUEL_SCORE count in auto (before bonus buckets)',
    category: 'fuel',
  },
  {
    id: 'avgTeleopFuelScore',
    label: 'Avg Teleop Raw',
    field: 'avgTeleopFuelScore',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average raw FUEL_SCORE count in teleop (before bonus buckets)',
    category: 'fuel',
  },
  {
    id: 'avgTotalPass',
    label: 'Avg Passes',
    field: 'avgTotalPass',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average fuel passes per match (auto + teleop)',
    category: 'fuel',
  },
  {
    id: 'passerRatio',
    label: 'Passer Ratio',
    field: 'passerRatio',
    aggregation: 'avg',
    format: 'number',
    decimals: 2,
    enabled: false,
    description: 'Ratio of passes to total activity (0 = pure scorer, 1 = pure passer)',
    category: 'fuel',
  },
  {
    id: 'totalTotalFuelEstimate',
    label: 'Total Fuel (Sum)',
    field: 'totalTotalFuelEstimate',
    aggregation: 'sum',
    format: 'number',
    decimals: 0,
    enabled: false,
    description: 'Sum of estimated fuel across all matches',
    category: 'fuel',
  },

  // ========== ENDGAME ==========
  {
    id: 'maxClimbLevel',
    label: 'Max Climb',
    field: 'computed',
    rawMetric: 'climbLevel',
    aggregation: 'max',
    format: 'climbLevel',
    decimals: 0,
    enabled: true,
    description: 'Highest climb level achieved in any match',
    category: 'endgame',
  },
  {
    id: 'level3ClimbCount',
    label: 'L3 Climb Count',
    field: 'level3ClimbCount',
    aggregation: 'sum',
    format: 'count',
    decimals: 0,
    enabled: true,
    description: 'Number of matches with Level 3 climb (shown as X/N)',
    category: 'endgame',
  },
  {
    id: 'level3ClimbRate',
    label: 'L3 Climb %',
    field: 'level3ClimbRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches with Level 3 climb',
    category: 'endgame',
  },
  {
    id: 'level2ClimbRate',
    label: 'L2 Climb %',
    field: 'level2ClimbRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches with Level 2 climb',
    category: 'endgame',
  },
  {
    id: 'level1ClimbRate',
    label: 'L1 Climb %',
    field: 'level1ClimbRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches with Level 1 climb',
    category: 'endgame',
  },
  {
    id: 'climbNoneRate',
    label: 'No Climb %',
    field: 'climbNoneRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches with no climb',
    category: 'endgame',
  },
  {
    id: 'climbFailedRate',
    label: 'Climb Failed %',
    field: 'climbFailedRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches where climb was attempted but failed',
    category: 'endgame',
  },
  {
    id: 'level2ClimbCount',
    label: 'L2 Climb Count',
    field: 'level2ClimbCount',
    aggregation: 'sum',
    format: 'count',
    decimals: 0,
    enabled: false,
    description: 'Number of matches with Level 2 climb (shown as X/N)',
    category: 'endgame',
  },
  {
    id: 'level1ClimbCount',
    label: 'L1 Climb Count',
    field: 'level1ClimbCount',
    aggregation: 'sum',
    format: 'count',
    decimals: 0,
    enabled: false,
    description: 'Number of matches with Level 1 climb (shown as X/N)',
    category: 'endgame',
  },
  {
    id: 'climbFailedCount',
    label: 'Climb Failed Count',
    field: 'climbFailedCount',
    aggregation: 'sum',
    format: 'count',
    decimals: 0,
    enabled: false,
    description: 'Number of matches where climb failed (shown as X/N)',
    category: 'endgame',
  },

  // ========== QUALITY ==========
  {
    id: 'dedicatedPasserRate',
    label: 'Ded. Passer %',
    field: 'dedicatedPasserRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches marked as dedicated passer',
    category: 'quality',
  },
  {
    id: 'bulldozedFuelRate',
    label: 'Bulldozed %',
    field: 'bulldozedFuelRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches where robot bulldozed fuel',
    category: 'quality',
  },
  {
    id: 'poorAccuracyRate',
    label: 'Poor Accuracy %',
    field: 'poorAccuracyRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches flagged for poor fuel scoring accuracy',
    category: 'quality',
  },
  {
    id: 'dedicatedPasserCount',
    label: 'Ded. Passer Count',
    field: 'dedicatedPasserCount',
    aggregation: 'sum',
    format: 'count',
    decimals: 0,
    enabled: false,
    description: 'Number of matches marked as dedicated passer (shown as X/N)',
    category: 'quality',
  },

  // ========== RELIABILITY ==========
  {
    id: 'lostConnectionRate',
    label: 'Lost Conn %',
    field: 'lostConnectionRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches with lost connection',
    category: 'reliability',
  },
  {
    id: 'noRobotRate',
    label: 'No Robot %',
    field: 'noRobotRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches with no robot on field',
    category: 'reliability',
  },
  {
    id: 'lostConnectionCount',
    label: 'Lost Conn Count',
    field: 'lostConnectionCount',
    aggregation: 'sum',
    format: 'count',
    decimals: 0,
    enabled: false,
    description: 'Number of matches with lost connection (shown as X/N)',
    category: 'reliability',
  },
  {
    id: 'noRobotCount',
    label: 'No Robot Count',
    field: 'noRobotCount',
    aggregation: 'sum',
    format: 'count',
    decimals: 0,
    enabled: false,
    description: 'Number of matches with no robot on field (shown as X/N)',
    category: 'reliability',
  },
];

// Category labels for display
export const CATEGORY_LABELS: Record<MetricCategory, string> = {
  overall: 'Overall Scoring',
  auto: 'Autonomous',
  teleop: 'Teleop',
  endgame: 'Endgame & Climbing',
  fuel: 'Fuel Scoring',
  quality: 'Quality Flags',
  reliability: 'Reliability',
};
