// Customizable Metrics Configuration

export type MetricAggregation = 'avg' | 'max' | 'min' | 'median' | 'sum' | 'rate';
export type MetricCategory = 'overall' | 'auto' | 'teleop' | 'endgame' | 'defense' | 'performance' | 'reliability';

export interface MetricColumn {
  id: string;
  label: string;
  field: string; // Field from TeamStatistics
  aggregation: MetricAggregation;
  format: 'number' | 'percentage' | 'time';
  decimals: number;
  enabled: boolean;
  description?: string;
  category: MetricCategory;
}

export interface MetricsConfig {
  columns: MetricColumn[];
  lastUpdated: string;
}

// All available metrics from TeamStatistics, organized by category
export const DEFAULT_METRICS: MetricColumn[] = [
  // ========== OVERALL ==========
  {
    id: 'avgTotalPoints',
    label: 'Avg Points',
    field: 'avgTotalPoints',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: true,
    description: 'Average total points per match',
    category: 'overall',
  },
  {
    id: 'maxTotalPoints',
    label: 'Max Points',
    field: 'maxTotalPoints',
    aggregation: 'max',
    format: 'number',
    decimals: 0,
    enabled: false,
    description: 'Maximum total points in a single match',
    category: 'overall',
  },
  {
    id: 'minTotalPoints',
    label: 'Min Points',
    field: 'minTotalPoints',
    aggregation: 'min',
    format: 'number',
    decimals: 0,
    enabled: false,
    description: 'Minimum total points in a single match',
    category: 'overall',
  },
  {
    id: 'avgAutoPoints',
    label: 'Avg Auto Pts',
    field: 'avgAutoPoints',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: true,
    description: 'Average autonomous points',
    category: 'overall',
  },
  {
    id: 'maxAutoPoints',
    label: 'Max Auto Pts',
    field: 'maxAutoPoints',
    aggregation: 'max',
    format: 'number',
    decimals: 0,
    enabled: false,
    description: 'Maximum auto points in a single match',
    category: 'overall',
  },
  {
    id: 'avgTeleopPoints',
    label: 'Avg Teleop Pts',
    field: 'avgTeleopPoints',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: true,
    description: 'Average teleop points',
    category: 'overall',
  },
  {
    id: 'maxTeleopPoints',
    label: 'Max Teleop Pts',
    field: 'maxTeleopPoints',
    aggregation: 'max',
    format: 'number',
    decimals: 0,
    enabled: false,
    description: 'Maximum teleop points in a single match',
    category: 'overall',
  },
  {
    id: 'avgEndgamePoints',
    label: 'Avg Endgame Pts',
    field: 'avgEndgamePoints',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average endgame points',
    category: 'overall',
  },
  {
    id: 'maxEndgamePoints',
    label: 'Max Endgame Pts',
    field: 'maxEndgamePoints',
    aggregation: 'max',
    format: 'number',
    decimals: 0,
    enabled: false,
    description: 'Maximum endgame points in a single match',
    category: 'overall',
  },

  // ========== AUTONOMOUS ==========
  {
    id: 'avgAutoFuelScored',
    label: 'Avg Auto FUEL',
    field: 'avgAutoFuelScored',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average FUEL scored in auto',
    category: 'auto',
  },
  {
    id: 'maxAutoFuelScored',
    label: 'Max Auto FUEL',
    field: 'maxAutoFuelScored',
    aggregation: 'max',
    format: 'number',
    decimals: 0,
    enabled: false,
    description: 'Maximum FUEL scored in auto',
    category: 'auto',
  },
  {
    id: 'avgAutoFuelMissed',
    label: 'Avg Auto Missed',
    field: 'avgAutoFuelMissed',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average FUEL missed in auto',
    category: 'auto',
  },
  {
    id: 'autoAccuracy',
    label: 'Auto Accuracy',
    field: 'autoAccuracy',
    aggregation: 'avg',
    format: 'percentage',
    decimals: 0,
    enabled: true,
    description: 'Auto shooting accuracy percentage',
    category: 'auto',
  },
  {
    id: 'autoMobilityRate',
    label: 'Mobility Rate',
    field: 'autoMobilityRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches with auto mobility',
    category: 'auto',
  },
  {
    id: 'autoClimbRate',
    label: 'Auto Climb Rate',
    field: 'autoClimbRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches attempting auto climb',
    category: 'auto',
  },
  {
    id: 'autoClimbSuccessRate',
    label: 'Auto Climb Success',
    field: 'autoClimbSuccessRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Success rate of auto climb attempts',
    category: 'auto',
  },

  // ========== TELEOP ==========
  {
    id: 'avgTeleopFuelScored',
    label: 'Avg Teleop FUEL',
    field: 'avgTeleopFuelScored',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average FUEL scored in teleop',
    category: 'teleop',
  },
  {
    id: 'maxTeleopFuelScored',
    label: 'Max Teleop FUEL',
    field: 'maxTeleopFuelScored',
    aggregation: 'max',
    format: 'number',
    decimals: 0,
    enabled: false,
    description: 'Maximum FUEL scored in teleop',
    category: 'teleop',
  },
  {
    id: 'avgTeleopFuelMissed',
    label: 'Avg Teleop Missed',
    field: 'avgTeleopFuelMissed',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average FUEL missed in teleop',
    category: 'teleop',
  },
  {
    id: 'teleopAccuracy',
    label: 'Teleop Accuracy',
    field: 'teleopAccuracy',
    aggregation: 'avg',
    format: 'percentage',
    decimals: 0,
    enabled: true,
    description: 'Teleop shooting accuracy percentage',
    category: 'teleop',
  },
  {
    id: 'avgCycleCount',
    label: 'Avg Cycles',
    field: 'avgCycleCount',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average cycles per match',
    category: 'teleop',
  },
  {
    id: 'maxCycleCount',
    label: 'Max Cycles',
    field: 'maxCycleCount',
    aggregation: 'max',
    format: 'number',
    decimals: 0,
    enabled: false,
    description: 'Maximum cycles in a single match',
    category: 'teleop',
  },
  {
    id: 'avgActiveHubScores',
    label: 'Avg Active Hub',
    field: 'avgActiveHubScores',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average scores during active hub',
    category: 'teleop',
  },
  {
    id: 'avgInactiveHubScores',
    label: 'Avg Inactive Hub',
    field: 'avgInactiveHubScores',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average scores during inactive hub',
    category: 'teleop',
  },

  // ========== ENDGAME ==========
  {
    id: 'climbAttemptRate',
    label: 'Climb Attempt %',
    field: 'climbAttemptRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches with climb attempt',
    category: 'endgame',
  },
  {
    id: 'level1ClimbRate',
    label: 'L1 Climb %',
    field: 'level1ClimbRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches with Level 1 climb',
    category: 'endgame',
  },
  {
    id: 'level2ClimbRate',
    label: 'L2 Climb %',
    field: 'level2ClimbRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches with Level 2 climb',
    category: 'endgame',
  },
  {
    id: 'level3ClimbRate',
    label: 'L3 Climb %',
    field: 'level3ClimbRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: true,
    description: 'Percentage of matches with Level 3 climb',
    category: 'endgame',
  },
  {
    id: 'avgClimbTime',
    label: 'Avg Climb Time',
    field: 'avgClimbTime',
    aggregation: 'avg',
    format: 'time',
    decimals: 1,
    enabled: false,
    description: 'Average climb time in seconds',
    category: 'endgame',
  },
  {
    id: 'minClimbTime',
    label: 'Best Climb Time',
    field: 'minClimbTime',
    aggregation: 'min',
    format: 'time',
    decimals: 1,
    enabled: false,
    description: 'Fastest climb time',
    category: 'endgame',
  },
  {
    id: 'avgEndgameFuelScored',
    label: 'Avg Endgame FUEL',
    field: 'avgEndgameFuelScored',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average FUEL scored in endgame',
    category: 'endgame',
  },

  // ========== DEFENSE ==========
  {
    id: 'defensePlayedRate',
    label: 'Plays Defense %',
    field: 'defensePlayedRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches playing defense',
    category: 'defense',
  },
  {
    id: 'avgDefenseEffectiveness',
    label: 'Defense Effect.',
    field: 'avgDefenseEffectiveness',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average defense effectiveness (0-4)',
    category: 'defense',
  },
  {
    id: 'wasDefendedRate',
    label: 'Was Defended %',
    field: 'wasDefendedRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches team was defended',
    category: 'defense',
  },
  {
    id: 'avgDefenseEvasion',
    label: 'Defense Evasion',
    field: 'avgDefenseEvasion',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average defense evasion rating (0-4)',
    category: 'defense',
  },

  // ========== PERFORMANCE ==========
  {
    id: 'avgDriverSkill',
    label: 'Driver Skill',
    field: 'avgDriverSkill',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average driver skill rating (1-5)',
    category: 'performance',
  },
  {
    id: 'avgIntakeSpeed',
    label: 'Intake Speed',
    field: 'avgIntakeSpeed',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average intake speed rating (1-5)',
    category: 'performance',
  },
  {
    id: 'avgShootingAccuracy',
    label: 'Shooting Acc Rating',
    field: 'avgShootingAccuracy',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average shooting accuracy rating (1-5)',
    category: 'performance',
  },
  {
    id: 'avgShootingSpeed',
    label: 'Shooting Speed',
    field: 'avgShootingSpeed',
    aggregation: 'avg',
    format: 'number',
    decimals: 1,
    enabled: false,
    description: 'Average shooting speed rating (1-5)',
    category: 'performance',
  },

  // ========== RELIABILITY ==========
  {
    id: 'noShowRate',
    label: 'No Show %',
    field: 'noShowRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches with no show',
    category: 'reliability',
  },
  {
    id: 'diedRate',
    label: 'Died %',
    field: 'diedRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches robot died',
    category: 'reliability',
  },
  {
    id: 'tippedRate',
    label: 'Tipped %',
    field: 'tippedRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches robot tipped',
    category: 'reliability',
  },
  {
    id: 'mechanicalIssuesRate',
    label: 'Mech Issues %',
    field: 'mechanicalIssuesRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches with mechanical issues',
    category: 'reliability',
  },
  {
    id: 'yellowCardRate',
    label: 'Yellow Card %',
    field: 'yellowCardRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches with yellow card',
    category: 'reliability',
  },
  {
    id: 'redCardRate',
    label: 'Red Card %',
    field: 'redCardRate',
    aggregation: 'rate',
    format: 'percentage',
    decimals: 0,
    enabled: false,
    description: 'Percentage of matches with red card',
    category: 'reliability',
  },
];

// Category labels for display
export const CATEGORY_LABELS: Record<MetricCategory, string> = {
  overall: 'Overall Scoring',
  auto: 'Autonomous',
  teleop: 'Teleop',
  endgame: 'Endgame & Climbing',
  defense: 'Defense',
  performance: 'Performance Ratings',
  reliability: 'Reliability',
};
